### ISSUE TITLE
Global quiz config

### ISSUE THREAD

**Issue by mp4096** [tum-rt/web-quiz#14]
* [x] Site metadata (favicon, title etc.)
* [ ] Custom HTML blobs for header
* [x] Custom HTML blobs for footer
* [x] About page (raw HTML)
* [x] Max questions number per session

**Comment by syxolk** [comment]
I don't know how integrate a real custom header with the current design. However, we already display the custom favicon and title.

**Comment by mp4096** [comment]
I'll close this issue for the time being. I plan on deploying the quiz in summer term 2017 without it and then we'll see.
