### ISSUE TITLE
Android stock browser fails to scale SVG math properly

### ISSUE THREAD

**Issue by syxolk** [tum-rt/web-quiz#17]
Steps to reproduce:
- Open Android Stock Browser
- Browse to your local web quiz instance http://192.168.*.*:3000
- Select tag 'math'
- Press 'Start quiz'

Version: Android 6.0.1, CyanogenMod 13.0

![screenshot_20161129-163251](https://cloud.githubusercontent.com/assets/6666063/20716483/a7fc908e-b652-11e6-90a8-fee01629b194.png)

**Comment by mp4096** [comment]
Awwww shit :hankey:

**Comment by syxolk** [comment]
Works fine with:
- Chrome 54 on Android
- Firefox 50 on Android

**Comment by mp4096** [comment]
:question: 
* http://codeandlife.com/2014/12/28/fixing-android-browser-svg-scaling-with-max-height/ 
* http://stackoverflow.com/questions/7570917/svg-height-incorrectly-calculated-in-webkit-browsers
* http://stackoverflow.com/questions/23128719/svg-object-scaling-in-android-browser

**Comment by syxolk** [comment]
Problem identified: Mathjax emits svg size with `ex` unit:

```
<svg width="8.976ex" height="2.676ex" ...
```

Converting that to
```
<svg width="89" height="26" ...
```
resolves the problem.

**Comment by syxolk** [comment]
`1ex`seems to be around `8px`.

**Comment by mp4096** [comment]
Great job! :+1:

One question, though: Wouldn't it be better to convert `ex` to `em` (of course only if Android browser displays `em` correctly)?

Maybe I'm a little paranoid, but I'm a little bit uneasy about converting a relative unit to an absolute unit. I checked the new version in Chromium and it seemed to rescale properly, but maybe there are some corner cases out there.

**Comment by syxolk** [comment]
Changing `<svg width="89" height="26" ...` to `<svg width="89em" height="26em" ...` makes no difference on Android stock browser. However, Chrome on Android scales the SVG with `em` to enormously huge size:

![screenshot_20161211-174215](https://cloud.githubusercontent.com/assets/6666063/21081543/6c9542a4-bfc9-11e6-9749-01eedf41e675.png)

**Comment by syxolk** [comment]
Using a factor of 0.5 and the `em` unit leads to the correct size on Chrome but fails again on the Android Browser.

The Android Browser just ignores the unit for `width` and `height`. I don't see any other solution than stripping the unit.

**Comment by mp4096** [comment]
Thanks for the investigation!

Ok, I see. Well, that's unfortunate. I just feel that we're planting a potential issue for the sake of supporting 10% of users. :cry:
