### ISSUE TITLE
Backslash yields to Yen sign in Chrome

### ISSUE THREAD

**Issue by syxolk** [tum-rt/web-quiz#20]
Steps to reproduce:
- Create question with this content:
```
uid: yen
tags: [yen]
content:
- text: This character \ should be a backslash
```

Yields to this text being displayed in Chrome:
![image](https://cloud.githubusercontent.com/assets/6666063/20863942/6fd2fc28-b9dd-11e6-990d-777c1732ce00.png)

This might have to do with this [Chromium Issue](https://bugs.chromium.org/p/chromium/issues/detail?id=305827) and the `font-family` defined for `body` by spectre.css:
```
font-family: "Helvetica Neue","PingFang SC","Hiragino Sans GB",
"Microsoft YaHei","Hiragino Kaku Gothic Pro",Meiryo,"Malgun Gothic",sans-serif;
```

**Comment by mp4096** [comment]
I think backslashes are not so relevant for us. The effort to fix this issue is too big compared to the benefit, so __wontfix__,
