### ISSUE TITLE
Improving Tag Behavior

### ISSUE THREAD

**Issue by syxolk** [tum-rt/web-quiz#22]
Instead of directly supporting a tag hierarchy, we can emulate one by using tag names that already contain the hierarchy.

Example:
```
- Control Systems
- Control Systems - Theory
- Control Systems - Practice
- Control Systems - Level A
- Control Systems - Level A - Theory
- Control Systems - Level A - Practice
- Control Systems - Level B
- Control Systems - Level B - Theory
- Control Systems - Level B - Practice
...
```

A particular question would now define these tags:
```
tags: [Control Systems, Control Systems - Level A, Control Systems - Level A - Practice,
    Control Systems - Practice]
```

## YAML Enhancements

To reduce the overhead by writing the whole hierarchy each time again, a special syntax could be introduced for the `tags` attribute:
```
tags: [[Control Systems, Level A, Practice], [Control Systems, Practice]]
```

## Startpage Enhancements

For better user assistance the Startpage can be enhanced as follows:

The user selected no tag so far. Behind every tag the number of questions with this tag are displayed.
```
- [ ] Control Systems (20)
- [ ] Control Systems - Theory (10)
- [ ] Control Systems - Practice (10)
- [ ] Control Systems - Level A (10)
- [ ] Control Systems - Level A - Theory (5)
- [ ] Control Systems - Level A - Practice (5)
- [ ] Control Systems - Level B (10)
- [ ] Control Systems - Level B - Theory (5)
- [ ] Control Systems - Level B - Practice (5)
```

The user selected the tag `Control Systems - Level A`. Behind every tag the number of questions that have this tag AND and `Control Systems - Level A` are displayed. For all tags with a number of 0, the tag is disabled (unclickable).

```
- [ ] Control Systems (10)
- [ ] Control Systems - Theory (5)
- [ ] Control Systems - Practice (5)
- [x] Control Systems - Level A (10)
- [ ] Control Systems - Level A - Theory (5)
- [ ] Control Systems - Level A - Practice (5)
- [ ] Control Systems - Level B (0) [DISABLED]
- [ ] Control Systems - Level B - Theory (0) [DISABLED]
- [ ] Control Systems - Level B - Practice (0) [DISABLED]
```

**Comment by syxolk** [comment]
It doesn't even make sense to have a tag like `Control Systems - Level A - Theory` now.

Choosing `Control Systems - Theory` together with `Control Systems - Level A` has the same effect.

**Comment by mp4096** [comment]
I am for a flat tag system. I don't think we can find a _one size fits all_ hierarchy.

I am also against composite tags like `Control Systems - Level A`. You can select `Control Systems`, `Level A` and `Theory` and have the same result.
