### ISSUE TITLE
Auto-Save Current Quiz State and Restore on Reload

### ISSUE THREAD

**Issue by syxolk** [tum-rt/web-quiz#25]
It can be really annoying to go back in history or swipe down (reload) by accident on mobile browsers. In the current state the whole quiz state is lost and the user has to redo everything again (even with other questions).

We can use `localStorage` to save the current state after pressing `Submit answers` on each page. If the app is loaded and there is something in `localStoarge` we try to restore the state.

**Comment by mp4096** [comment]
I think it's a very nice feature, but I'm not sure about how much coding effort it will be.

For instance, Do you want to store all the content locally in order to show the results page without extra server requests?

**Comment by syxolk** [comment]
We don't need any additional requests to show the results page or to save/load the quiz state.

Fixed with commit 6cfb353a5e1d2b1a36cc1d999ea0f749a9a00810
