### ISSUE TITLE
Broken check mark symbols

### ISSUE THREAD

**Issue by mp4096** [tum-rt/web-quiz#27]
d718fc3498def4565eb66df76f69affb6c435222 introduced a peculiar bug: If you start app in the dev mode, the check mark is broken (just tap on any tag in the main menu). If you start a production run, everything's ok. I can reproduce this bug with Chromium 55.0.2883.87 and Pale Moon 27.1.0.

The console's silent.

**Comment by syxolk** [comment]
Seems to be a problem caused by the transition from `file-loader` 0.9.0 to 0.10.0

**Comment by mp4096** [comment]
ada8a4dec8bffd20d486fc33dedef2ddeb2d24e4 solves the issue for me.

Actually, I suspected the pinned `webpack` version to be the culprit, or---It was a major version increase, right?---`vue-i18n`. `file-loader` changes should have been backwards-compatible, right? :crying_cat_face: 

![semver](https://cloud.githubusercontent.com/assets/5394551/22857818/495674ce-f0ad-11e6-8fd3-812a3f5bdf40.jpg)

**Comment by syxolk** [comment]
`file-loader` is still in 0.x and according to [semver.org](http://semver.org) the version has no special meaning before 1.x:
>Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Note the `x>0` condition:
> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API.

**Comment by mp4096** [comment]
Awww shucks, you're totally right. Come to think about it, in `indentex` I increased minor versions while still in `0.x` [to indicate breaking changes](https://github.com/mp4096/indentex/commit/4b71c5170804555d8820daeb365c4c86505cb20b).

Well, this is awkward. :blush:

**Comment by mp4096** [comment]
See, I go on vacation, drink too much beer and already cannot interpret semver correctly.
