### ISSUE TITLE
Spectre update

### ISSUE THREAD

**Issue by mp4096** [tum-rt/web-quiz#28]
Uhm, opening an issue to track all changes.

Although @syxolk addressed a lot of issues in f3f35158049dce5c8fac89e7d04736799829fcb4 and b3dc6061900bb89086b2d98786242dfffae1f7e1, we still have some regressions.

One of them is the vertical space between questions in the evaluation view:

Before:

![before](https://cloud.githubusercontent.com/assets/5394551/23620878/e1186590-0298-11e7-95cc-216f1503ea56.png)

After:

![after](https://cloud.githubusercontent.com/assets/5394551/23620880/e24bba3e-0298-11e7-9456-0c5265fecc2a.png)

**Comment by syxolk** [comment]
Also fixed this gap with commit f74028687915501f8850963b0d097fa826fadb6a:

![image](https://cloud.githubusercontent.com/assets/6666063/23657000/5b0bba84-033c-11e7-9e81-419d92924627.png)

**Comment by mp4096** [comment]
Cool, looks great! :+1: 

I noticed one more thing:
![height_mismatch](https://cloud.githubusercontent.com/assets/5394551/23662475/07ee29f4-0350-11e7-9ee6-72a950559427.png)

**Comment by syxolk** [comment]
Ahh, I'm starting to hate CSS frameworks.

**Comment by syxolk** [comment]
For the time being, I cherry-picked all commits that fixed problems that were already present on `master`.

**Comment by syxolk** [comment]
So that you don't be surprised: I merged two commits, dropped the ones I've cherry-picked and rebased the whole thing on master.

**Comment by syxolk** [comment]
What a strange error btw.: https://travis-ci.org/tum-rt/web-quiz/jobs/208952054

**Comment by mp4096** [comment]
Meh. https://travis-ci.org/tum-rt/web-quiz/jobs/208952054

**Comment by mp4096** [comment]
> So that you don't be surprised: I merged two commits, dropped the ones I've cherry-picked and rebased the whole thing on master.

`#mindblown`

![cena](https://cloud.githubusercontent.com/assets/5394551/23710242/55c5dd26-041c-11e7-84f3-eb38948e0b53.gif)

**Comment by mp4096** [comment]
Sorry, I forgot that I'm an Adventure Time fan.

![finn](https://cloud.githubusercontent.com/assets/5394551/23710320/9aa099cc-041c-11e7-9f8c-62f04924706a.gif)

**Comment by mp4096** [comment]
Ok, I cannot find any other regressions.
