### ISSUE TITLE
Tests + CI

### ISSUE THREAD

**Issue by mp4096** [tum-rt/web-quiz#3]
I'm not a TDD fan, but we must keep tests in mind. 

@syxolk Would be great if you could implement a couple of very simple tests for the backend, I'd take a look at them and try to write my own.

**Comment by syxolk** [comment]
- [ ] [CodeClimate](https://codeclimate.com)
- [ ] [Codacy](https://www.codacy.com)

Deployment:
- [ ] [Dockerfile](https://docs.docker.com/engine/reference/builder/)
- [ ] [Dply](https://dply.co/)

**Comment by mp4096** [comment]
Any chance we can deploy to the [LRZ compute cloud](https://www.lrz.de/services/compute/cloud_en/)? I read the manual but didn't get whether it is a good platform for a web server.

I'll contact LRZ one of these days.

**Comment by mp4096** [comment]
BTW,

- [ ] [David](https://david-dm.org/)

**Comment by mp4096** [comment]
Oops, didn't see your last commit, sorry.

**Comment by syxolk** [comment]
- [Codacy](https://www.codacy.com/wizard/projects) won't allow me to add web-quiz as a project.
- [CodeClimate](https://codeclimate.com/github/tum-rt/web-quiz) checked the `dev` branch but doesn't server any badges for it (only `master`)

**Comment by mp4096** [comment]
I've authorised Codacy and it seems like it doesn't like `dev` too.

I'd suggest we move the development over to master, I'm tired of changing branches every time I open the repo.

**Comment by mp4096** [comment]
Oh, Codacy does allow you to select the branch to work with.

**Comment by syxolk** [comment]
> Any chance we can deploy to the LRZ compute cloud? I read the manual but didn't get whether it is a good platform for a web server.

Looks promising. Would be great, if they provide a server similar to a small Amazon EC2 instance.

**Comment by syxolk** [comment]
How about [Appveyor](https://www.appveyor.com/)?

**Comment by mp4096** [comment]
Honestly, I don't want to support development on Windows. So I say nay.
