### ISSUE TITLE
Tags with 0 questions are not disabled

### ISSUE THREAD

**Issue by syxolk** [tum-rt/web-quiz#34]
Not working for commit a2b0fc896bd115bd418dd31560184f594fcd192d

![image](https://cloud.githubusercontent.com/assets/6666063/23863996/860005ae-0811-11e7-8f59-36d4c8c71ab8.png)

Still working for commit fc26ff621fe5cdac980f1577b92b0c98d270f220

![image](https://cloud.githubusercontent.com/assets/6666063/23864066/b7a144b0-0811-11e7-883f-3e9debc0713a.png)

**Comment by mp4096** [comment]
https://www.youtube.com/watch?v=MIZbGSXeWWE

It's probably `spectre`... will you dig into it or should I do it?

**Comment by syxolk** [comment]
It must be something with the `disabled` class and `pointer-events: none;`, but I couldn't find it yet.

**Comment by syxolk** [comment]
Quel surprise: https://github.com/picturepan2/spectre/commit/55cf3304d19423d1f2d426f924217e6a4693ff06

**Comment by mp4096** [comment]
Läuft.
