### ISSUE TITLE
Image scaling

### ISSUE THREAD

**Issue by mp4096** [tum-rt/web-quiz#41]
Currently, images are scaled to the main column width. It is ok for photos, but it leads to problems if images contain fixed-size text. Example:

This image

![image](https://cloud.githubusercontent.com/assets/5394551/25635253/c08d932e-2f7d-11e7-9908-8dbc7365cc1e.png)

compared to this:

![image](https://cloud.githubusercontent.com/assets/5394551/25635284/e3332ad8-2f7d-11e7-8f5c-dbacedaff516.png)

Maybe we can add an optional field to the image element which specifies the desired image width in percent? And default to 100% is it is not specified.

**Comment by syxolk** [comment]
Should we center the images then?

**Comment by mp4096** [comment]
Yes, I cannot think of a use case when you would like to left or right align it.

**Comment by mp4096** [comment]
Nice:

![image](https://cloud.githubusercontent.com/assets/5394551/25757190/de729f12-31c9-11e7-82c0-a24235287b75.png)

**Comment by mp4096** [comment]
I reopen this issue since I want to add an example for this feature.
