### ISSUE TITLE
Node v8.0 support

### ISSUE THREAD

**Issue by mp4096** [tum-rt/web-quiz#43]
[Node v8.0 has been released.](https://nodejs.org/en/blog/release/v8.0.0/)

I think we should also drop Node v4.0 support / CI completely.

**Comment by mp4096** [comment]
@syxolk Looking at [this roadmap](https://nodejs.org/en/blog/release/v8.0.0/#long-term-support), maybe it's reasonable to drop both 4 and 5 and move 7 to `allow_failure`?

**Comment by syxolk** [comment]
Yeah, Node 5 has been dead for a long time already.

**Comment by mp4096** [comment]
Ok, then let's prune it off.
