### ISSUE TITLE
Spectre bumped to 0.5

### ISSUE THREAD

**Issue by mp4096** [tum-rt/web-quiz#45]
Ho ho ho, here we go again! Spectre now has a different root font size, so I guess we'll have fun fixing up regressions due to hardcoded sizes.

**Comment by mp4096** [comment]
Looks like 'only' object sizes have been broken, the rest seems to be ok (apart from #46)

![image](https://user-images.githubusercontent.com/5394551/31221081-d3019040-a9c2-11e7-812e-71dc71b679ed.png)

**Comment by syxolk** [comment]
Fixed flex box and added `text-overflow: ellipsis;`. Look like this now:

![image](https://user-images.githubusercontent.com/6666063/35800633-d59d5138-0a69-11e8-864b-dfa6ce41870d.png)

**Comment by mp4096** [comment]
:+1:

Does it work with Spectre 0.5 as well?

**Comment by syxolk** [comment]
Yes and no. It seems like they removed `grid-480`. But that's another issue.

**Comment by mp4096** [comment]
Ok. Can you make it work with 0.5 please? :cat2:

**Comment by syxolk** [comment]
Seems to be fixed now. I had to add a lot of boilerplate for all kinds of broken stuff.

We might have to switch to bootstrap in te future, this is just super annoying.

**Comment by syxolk** [comment]
![image](https://user-images.githubusercontent.com/6666063/35806045-6daca6ea-0a7e-11e8-9353-a6a9e15aeabd.png)
