### ISSUE TITLE
Question tabs in the results view are not working anymore

### ISSUE THREAD

**Issue by mp4096** [tum-rt/web-quiz#46]
I went as far back as to a8b821e90b14055eec97ba290fc536ed6d53e46b 

Somehow tabs are not working anymore, neither in Chromium 61.0.3163.79 nor in Pale Moon 27.4.2. The console is silent. :confused:

**Comment by syxolk** [comment]
[It seems like `document.body.scrollTop` is deprecated.](https://stackoverflow.com/a/28633515)

**Comment by mp4096** [comment]
Ok. Why weren't there any deprecation messages though? Whatever. Can you fix it?

**Comment by syxolk** [comment]
I'm still investigating.

So far:
- Chrome only supports `document.documentElement.scrollTop`
- Edge only supports `document.body.scrollTop`

**Comment by mp4096** [comment]
![eyeroll](https://user-images.githubusercontent.com/5394551/31298673-8eef2320-aaeb-11e7-9c2f-986b7c3b5fc7.gif)

**Comment by syxolk** [comment]
According to https://miketaylr.com/posts/2014/11/document-body-scrolltop.html we wanna use this:

```
(document.documentElement ||
 document.body.parentNode ||
 document.body).scrollTop;
```

But there's also [`document.scrollingElement`](https://developer.mozilla.org/en-US/docs/Web/API/document/scrollingElement) so maybe i will include it as well, leading to:

```
(document.scrollingElement ||
 document.documentElement ||
 document.body.parentNode ||
 document.body).scrollTop;
```

**Comment by mp4096** [comment]
TBH I'm totally confused. We're not talking about some obscure functionality, but about tabbing, which is probably used by a ton of websites. How come it's so hard?

**Comment by syxolk** [comment]
> In Blink and WebKit browsers, it's the exact opposite. Both have attempted to implement the standard (safari, chrome), but both have had to back out their patches due to sites breaking (some Google properties and webkit.org among them, as luck would have it).
> The bug that was filed against WebKit for Facebook breaking as a result of changing to the standard is especially interesting because it shows the tension between following standards (and other browsers) and breaking sites for their own users.

**Comment by mp4096** [comment]
Web is hard. :frowning_woman:

**Comment by syxolk** [comment]
Ok, Edge has `document.documentElement.scrollTop` but it's always set to `0`, so the `||`-expression thing does not work here.

However, every browser except MSIE supports `document.scrollingElement`. MSIE works with `document.documentElement`. So this is sufficient:

```
(document.scrollingElement || document.documentElement).scrollTop
```

**Comment by syxolk** [comment]
The fix does not work in Android stock browser.

**Comment by syxolk** [comment]
It's slowly getting interesting.

**Comment by mp4096** [comment]
I will be more than happy to drop support for Android stock browser. Remember #17?

**Comment by mp4096** [comment]
BTW, can we test for this programatically, e.g. from Karma?

**Comment by syxolk** [comment]
> BTW, can we test for this programatically, e.g. from Karma?

#49
