### ISSUE TITLE
Supported Browsers

### ISSUE THREAD

**Issue by syxolk** [tum-rt/web-quiz#6]
What browser+version should we support?

Vue.js seems to target Chrome, Firefox, Safari and IE > 8. We should also support Android stock browser, Chrome, Android and Safari on iOS and Edge on Win10.

CI+Fronted Testing:
- Vue uses [Saucelabs](https://saucelabs.com/pricing) but they don't have free plans.
- [Phantom.js](http://phantomjs.org/headless-testing.html) has headless testing but only for Webkit.
- [Selenium](http://docs.seleniumhq.org/) looks also nice, especially their Node.js binding [WebdriverIO](http://webdriver.io/)

**Comment by mp4096** [comment]
Hm. My priorities would be (from most important to less important):
1. Safari on iOS
* Chrome on Android
* Stock Android browser
* Firefox on Android
* Chrome on Windows 7/10
* Firefox on Windows 7/10
* Safari on macOS
* Edge on Windows 10

I wouldn't bother about IE at all.

As for the CI: Let us discuss it in person on Monday or Tuesday.

**Comment by syxolk** [comment]
Works surprisingly well on IE 11, only the radio buttons/checkboxes are not clickable if they contain math,

**Comment by syxolk** [comment]
[Karma](https://github.com/karma-runner/karma)!

**Comment by mp4096** [comment]
Uhm, SauceLabs does have free plans: https://saucelabs.com/open-source

**Comment by syxolk** [comment]
Using `dist: trusty` together with `Xvfb`, travis is able to start karma and execute the test scripts for
- Mozilla Firefox 38.4.0
- Chromium 53.0.2785.143

**Comment by syxolk** [comment]
I've found the open source sign-up for Saucelabs. Together with [karma-sauce-launcher](https://github.com/karma-runner/karma-sauce-launcher) I was able to test for all platforms except Firefox on Android. I think, Travis can trigger the saucelabs build automatically for us.

**Comment by mp4096** [comment]
Great! Where was it actually?

Quite a pity about Firefox on Android. What's the problem exactly?

**Comment by syxolk** [comment]
The sign-up button on bottom of https://saucelabs.com/open-source goes to https://saucelabs.com/beta/signup/OSS/None which is another one than for the 'Free Trial' sign-up https://saucelabs.com/signup/trial . It's also impossible to enable the open-source plan for accounts created with a Github login.

Saucelabs doesn't tell us which browsers they support on Android, only which emulators they have. https://saucelabs.com/platforms
I think they don't support stock browser either, only 'Chrome Mobile'

**Comment by syxolk** [comment]
Saucelabs browser-matrix is working as well:

[![Sauce Test Status](https://saucelabs.com/browser-matrix/web-quiz.svg)](https://saucelabs.com/u/web-quiz)
