### ISSUE TITLE
Question schema enhancements

### ISSUE THREAD

**Issue by syxolk** [tum-rt/web-quiz#8]
What the YAML format probably needs:

- [x] Text that is only shown on the result screen.
- [x] Multiple answers for `task_text` (*Gauss* or *Gauß*?)
- [x] Ignore case mode for `task_text` (*Gauß* or *gauß*?)

**Comment by mp4096** [comment]
> Text that is only shown on the result screen.

Yep, I'll add it.

> Multiple answers for `task_text` (_Gauss_ or _Gauß_?)

Yep, unfortunately this will be a breaking change.

> Ignore case mode for `task_text` (_Gauß_ or _gauß_?)

I'd say we perform only case-insensitive comparison.
